apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yyigz7919-python 
  janus-idp.io/tekton: yyigz7919-python
  backstage.io/kubernetes-id: yyigz7919-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yyigz7919-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml